### ISSUE TITLE
Cannot log in on non-localhost browser

### ISSUE THREAD

**Issue by msmit250** [openenergysolutions/openfmb.hmi#15]
On the machine that is running openfmb.hmi in docker, I can log into the HMI via the default admin/hm1admin credentials (at 127.0.0.1:32771). However, navigating to [ip_address]:32771 from a different machine presents the login screen, but does not allow user to log in via the same credentials. "Invalid username or password" is returned. Additionally, popup "you do not have access to this page!" is shown before login is attempted.

**Comment by corynguyenfl** [comment]
Hello @msmit250,
In your ```config/app.yaml``` file, the ```server_host``` should be the ip address of the machine where the HMI is running on.  Please clear your browser cache (remote computer) and try again.

**Comment by msmit250** [comment]
That worked perfectly! I'm now running into a different connection related issue I was hoping you could help with:

We're running the demo behind an Nginx reverse proxy, with SSL certificates configured. When attempting to access the server via secure connection (https://demo.example.com), the browser will not allow the page to load due to the software attempting to load some assets via HTTP. Here is the browser error:

Mixed Content: The page at 'https://demo.example.com/sessions/signin?return=%2Fhome' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://10.0.10.28:32771/login'. This request has been blocked; the content must be served over HTTPS.

**Comment by corynguyenfl** [comment]
In the app.toml file, ```hmi``` section, please try to specify the certificate/key and protocol schemes as below:

```toml
[hmi]
server_host = "localhost"
server_port = 32771 # available ports are: 80 8080 443 32771 42771
ssl = true
ssl_cert = "ca-cert.pem"
ssl_key = "ca.key"
http_scheme = "https"
ws_scheme = "wss"

```
